export const ArText = {
    tafweej: 'تفــــــــــويــــــــــج',
    login: 'دخول',
    mobileNumber: 'رقم الجوال',
    password: 'كلمة المرور',
    forgetPassword: 'نسيت كلمة المرور؟',
    enterMobileNumber: 'أدخل رقم الجوال',
    resetPassword: 'استعادة كلمة المرور',
    skip: 'تخطي',
    analytic: 'احصائيات',
    prayer: 'اقرب موعد صلاة',
    weather: 'درجة الحرارة',
    remainingTime: 'الوقت المتبقي للفوج القادم',
    totalBatches: 'عدد الافواج الكلي',
    doneTafweej: 'تم تفويجها',
    didntDoTafweej: 'لم يتم تفويجها',
    remain: 'تبقى',
    readiness: 'تحديد الجاهزية',
    accommodation: 'تسكين',
    saveBtn: 'حفظ',
    batches: 'الأفواج',
    guides: 'مرشدين',
    theGuides: 'المرشدين',
    addGuide: 'إضافة مرشد',
    add: 'إضافة',
    name: 'الاسم',
    guideSearch: 'بحث باسم مرشد',
    showAll: 'عرض الجميع',
    deleteGuide: 'حذف',
    assignBatch: 'اسناد',
    confirmDeleteGuide: 'هل انت متأكد من حذف المرشد؟',
    notifications: 'الاشعارات',
    latestNotifications: 'اخر الاشعارات',
    oldNotifications: 'اشعارات سابقة',
    guideProfile: 'الصفحة الشخصية',
    allBatches: 'كل الأفواج',
    upcomingBatches: 'الرحلات القادمة',
    prayerTimes: 'أوقات الصلاة',
    tafweejIsDone: 'تم التفويج',
    foujNotOutYet: 'الافواج التي لم يتم تفويجها',
    foujDone: 'الافواج التي تم تفويجها',
    remainingBatches: 'الافواج المتبقية',
    since: 'منذ',
    timeRemain: 'مبتقي',
    previousBatch: 'الفوج السابق',
    nextBatch: 'الفوج القادم',
    confirmTrip: 'اعتماد الجولة',
    hour: 'الساعة',
    tempDegree: 'درجة الحرارة',
    status: 'الحالة',
    numberOfPilgrims: 'عدد الحجاج',
    numberOfPilgrimsAlertMsg: 'ddd',
    number: 'العدد'

}