export const ArText = {
    tafweej: 'تفــــــــــويــــــــــج',
    login: 'دخول',
    mobileNumber: 'رقم الجوال',
    password: 'كلمة المرور',
    forgetPassword: 'نسيت كلمة المرور؟',
    enterMobileNumber: 'أدخل رقم الجوال',
    resetPassword: 'استعادة كلمة المرور',
    skip: 'تخطي',
    analytic: 'احصائيات',
    prayer: 'اقرب موعد صلاة',
    weather: 'درجة الحرارة',
    remainingTime: 'الوقت المتبقي للفوج القادم',
    totalBatches: 'عدد الافواج الكلي',
    doneTafweej: 'تم تفويجها',
    didntDoTafweej: 'لم يتم تفويجها',
    remain: 'تبقى',
    readiness: 'تحديد الجاهزية',
    accommodation: 'تسكين',
    saveBtn: 'حفظ',
    batches: 'الأفواج',
    guides: 'مرشدين',
    theGuides: 'المرشدين',
    addGuide: 'إضافة مرشد',
    add: 'إضافة',
    name: 'الاسم',
    guideSearch: 'بحث باسم مرشد',
    showAll: 'عرض الجميع',
    deleteGuide: 'حذف',
    assignBatch: 'اسناد',
    confirmDeleteGuide: 'هل انت متأكد من حذف المرشد؟'

}